# Copyright (C) 2013-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
# Copyright (C) 2020 Android Ice Cold Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/m7/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/htc/m7/proprietary/etc/firmware/BCM4335B0_002.001.006.0296.0297.hcd:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/BCM4335B0_002.001.006.0296.0297.hcd
PRODUCT_COPY_FILES += \
    vendor/htc/m7/proprietary/bin/efsks:$(TARGET_COPY_OUT_SYSTEM)/bin/efsks \
    vendor/htc/m7/proprietary/bin/netmgrd:$(TARGET_COPY_OUT_SYSTEM)/bin/netmgrd \
    vendor/htc/m7/proprietary/bin/qcks:$(TARGET_COPY_OUT_SYSTEM)/bin/qcks \
    vendor/htc/m7/proprietary/bin/qmuxd:$(TARGET_COPY_OUT_SYSTEM)/bin/qmuxd \
    vendor/htc/m7/proprietary/lib/libdiag.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdiag.so \
    vendor/htc/m7/proprietary/lib/libdsi_netctrl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdsi_netctrl.so \
    vendor/htc/m7/proprietary/lib/libdsutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdsutils.so \
    vendor/htc/m7/proprietary/lib/libidl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libidl.so \
    vendor/htc/m7/proprietary/lib/libnetmgr.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libnetmgr.so \
    vendor/htc/m7/proprietary/lib/libqcci_legacy.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqcci_legacy.so \
    vendor/htc/m7/proprietary/lib/libqdi.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqdi.so \
    vendor/htc/m7/proprietary/lib/libqdp.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqdp.so \
    vendor/htc/m7/proprietary/lib/libqmi.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqmi.so \
    vendor/htc/m7/proprietary/lib/libqmi_cci.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqmi_cci.so \
    vendor/htc/m7/proprietary/lib/libqmi_client_qmux.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqmi_client_qmux.so \
    vendor/htc/m7/proprietary/lib/libqmi_common_so.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqmi_common_so.so \
    vendor/htc/m7/proprietary/lib/libqmi_csi.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqmi_csi.so \
    vendor/htc/m7/proprietary/lib/libqmi_encdec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqmi_encdec.so \
    vendor/htc/m7/proprietary/lib/libqmiservices.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqmiservices.so \
    vendor/htc/m7/proprietary/lib/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libril-qc-qmi-1.so \
    vendor/htc/m7/proprietary/lib/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libril-qcril-hook-oem.so
